skills_list = [
    ".NET (5+)",
    ".NET Framework (1.0 - 4.8)",
    ".NET MAUI",
    "APT",
    "ASP.NET",
    "ASP.NET CORE",
    "Accountability",
    "Ada",
    "Adaptability",
    "Alibaba Cloud",
    "Amazon Web Services (AWS)",
    "Analytical Thinking",
    "Angular",
    "AngularJS",
    "Ansible",
    "Ant",
    "Apache Kafka",
    "Apache Spark",
    "Apex",
    "Assembly",
    "Astro",
    "Attention to Detail",
    "Bash/Shell (all shells)",
    "BigQuery",
    "Blazor",
    "Bun",
    "Business Intelligence",
    "C",
    "C#",
    "C++",
    "CUDA",
    "Capacitor",
    "Cassandra",
    "Chef",
    "Chocolatey",
    "Clickhouse",
    "Clojure",
    "Cloud Firestore",
    "Cloudflare",
    "Cobol",
    "Cockroachdb",
    "CodeIgniter",
    "Collaboration",
    "Colocation",
    "Composer",
    "Cordova",
    "Cosmos DB",
    "Couch DB",
    "Couchbase",
    "Creative Thinking",
    "Critical Thinking",
    "Crystal",
    "Dagger",
    "Dart",
    "Dashboarding",
    "Data Analytics",
    "Data Cleaning",
    "Data Engineering",
    "Data Science",
    "Data Visualization",
    "Databricks",
    "Databricks SQL",
    "Datawrapper",
    "Datomic",
    "Delphi",
    "Deno",
    "Digital Ocean",
    "DirectX",
    "Django",
    "Docker",
    "Drupal",
    "DuckDB",
    "Dynamodb",
    "EDA",
    "ETL",
    "Elasticsearch",
    "Electron",
    "Elixir",
    "Elm",
    "Erlang",
    "EventStoreDB",
    "Excel",
    "Express",
    "F#",
    "Fast Learner",
    "FastAPI",
    "Fastify",
    "Firebase",
    "Firebase Realtime Database",
    "Firebird",
    "Flask",
    "Flexibility",
    "Flutter",
    "Fly.io",
    "Fortran",
    "GDScript",
    "GTK",
    "Gatsby",
    "Go",
    "Goal-Oriented",
    "Godot",
    "Google Cloud",
    "Google Data Studio",
    "Google Sheets",
    "Google Test",
    "Gradle",
    "Groovy",
    "H2",
    "HTML/CSS",
    "Hadoop",
    "Haskell",
    "Heroku",
    "Hetzner",
    "Homebrew",
    "Htmx",
    "Hugging Face Transformers",
    "IBM Cloud Or Watson",
    "IBM DB2",
    "Independent Work",
    "InfluxDB",
    "Initiative",
    "Ionic",
    "JAX",
    "Java",
    "JavaScript",
    "Julia",
    "Keras",
    "Kotlin",
    "Ktor",
    "Kubernetes",
    "Laravel",
    "Leadership",
    "Linode, now Akamai",
    "Lisp",
    "Looker",
    "Lua",
    "MATLAB",
    "MFC",
    "MS Excel",
    "MSBuild",
    "Make",
    "Managed Hosting",
    "MariaDB",
    "Matplotlib",
    "Maven (build tool)",
    "Metabase",
    "MicroPython",
    "Microsoft Access",
    "Microsoft Azure",
    "Microsoft Excel",
    "Microsoft SQL Server",
    "MongoDB",
    "MySQL",
    "Neo4J",
    "NestJS",
    "Netlify",
    "Next.js",
    "Nim",
    "Ninja",
    "Nix",
    "Node.js",
    "NuGet",
    "NumPy",
    "Nuxt.js",
    "OCaml",
    "OVH",
    "Objective-C",
    "OpenCL",
    "OpenGL",
    "OpenShift",
    "OpenStack",
    "Opencv",
    "Oracle",
    "Oracle Cloud Infrastructure (OCI)",
    "PHP",
    "Pacman",
    "Pandas",
    "Perl",
    "Phoenix",
    "Pip",
    "Play Framework",
    "Podman",
    "PostgreSQL",
    "Power BI",
    "PowerBI",
    "PowerShell",
    "Presto",
    "Problem Solving",
    "Prolog",
    "Pulumi",
    "Puppet",
    "Python",
    "PythonAnywhere",
    "Qt",
    "Quarkus",
    "R",
    "RabbitMQ",
    "RavenDB",
    "React",
    "React Native",
    "Redis",
    "Remix",
    "Render",
    "Reporting",
    "Roslyn",
    "Ruby",
    "Ruby on Rails",
    "Ruff",
    "Rust",
    "SQL",
    "SQLite",
    "Scala",
    "Scaleway",
    "Scikit-Learn",
    "Seaborn",
    "Self-motivation",
    "Sheets",
    "Snowflake",
    "Solid.js",
    "Solidity",
    "Solr",
    "Spreadsheets",
    "Spring Boot",
    "Spring Framework",
    "Strapi",
    "Strategic Thinking",
    "Strong Communication",
    "Supabase",
    "Superset",
    "Svelte",
    "Swift",
    "SwiftUI",
    "Symfony",
    "Tableau",
    "Tauri",
    "Teamwork",
    "TensorFlow",
    "Terraform",
    "TiDB",
    "Tidyverse",
    "Time Management",
    "Torch/PyTorch",
    "TypeScript",
    "Unity 3D",
    "Unreal Engine",
    "VBA",
    "VMware",
    "Vercel",
    "Visual Basic (.Net)",
    "Visual Studio Solution",
    "Vite",
    "Vue.js",
    "Vultr",
    "Webpack",
    "WordPress",
    "Work Ethic",
    "Xamarin",
    "Yarn",
    "Yii 2",
    "Zephyr",
    "Zig",
    "jQuery",
    "mlflow",
    "npm",
    "pnpm",
]
