name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> backend/.env
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> backend/.env
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> backend/.env

    - name: Run tests
      run: |
        cd backend
        pytest